using System.Reflection;
using NUnit.Framework;
using ThanhDV.SaveKeeper.Core;
using ThanhDV.SaveKeeper.Editor;

namespace ThanhDV.SaveKeeper.Tests.Editor
{
    /// <summary>
    /// Tests the formatting helpers and content builders of <see cref="SaveKeeperSettingsGenerator"/>
    /// via reflection. End-to-end Generate() with file I/O is not exercised here because the hardcoded
    /// output path lives inside <c>Assets/</c> and a write would side-effect the consumer project.
    /// The pure-function tests below give high confidence the public Generate() produces correct output.
    /// </summary>
    public class SaveKeeperSettingsGeneratorTests
    {
        #region BuildCsContent — shape

        [Test]
        public void BuildCsContent_HasAutoGeneratedHeader()
        {
            string output = InvokeBuildCsContent(new SaveSettings());
            Assert.That(output, Does.Contain("// <auto-generated />"));
        }

        [Test]
        public void BuildCsContent_HasCoreNamespaceAndFactoryClass()
        {
            string output = InvokeBuildCsContent(new SaveSettings());
            Assert.That(output, Does.Contain("namespace ThanhDV.SaveKeeper.Core"));
            Assert.That(output, Does.Contain("public static class SaveKeeperSettings"));
            Assert.That(output, Does.Contain("public static SaveSettings Create()"));
        }

        #endregion

        #region BuildCsContent — defaults

        [Test]
        public void BuildCsContent_DefaultSettings_EmitsExpectedDefaults()
        {
            string output = InvokeBuildCsContent(new SaveSettings());
            Assert.That(output, Does.Contain("UseEncryption = true"));
            Assert.That(output, Does.Contain("FileName = \"Default\""));
            Assert.That(output, Does.Contain("SaveExtension = \".sav\""));
            Assert.That(output, Does.Contain("MetaExtension = \".meta\""));
            Assert.That(output, Does.Contain("EnableAutoSave = true"));
            Assert.That(output, Does.Contain("AutoSaveTime = 300f"));
            Assert.That(output, Does.Contain("AutoSaveOnQuit = true"));
            Assert.That(output, Does.Contain("AutoSaveOnQuitTimeout = 3000"));
        }

        #endregion

        #region BuildCsContent — custom values

        [Test]
        public void BuildCsContent_BoolFlipsReflectInOutput()
        {
            string output = InvokeBuildCsContent(new SaveSettings
            {
                UseEncryption = false,
                EnableAutoSave = false,
                AutoSaveOnQuit = false,
            });
            Assert.That(output, Does.Contain("UseEncryption = false"));
            Assert.That(output, Does.Contain("EnableAutoSave = false"));
            Assert.That(output, Does.Contain("AutoSaveOnQuit = false"));
        }

        [Test]
        public void BuildCsContent_FloatUsesInvariantCultureFSuffix()
        {
            string output = InvokeBuildCsContent(new SaveSettings { AutoSaveTime = 0.5f });
            Assert.That(output, Does.Contain("AutoSaveTime = 0.5f"));
        }

        [Test]
        public void BuildCsContent_IntegerNoSuffix()
        {
            string output = InvokeBuildCsContent(new SaveSettings { AutoSaveOnQuitTimeout = 1234 });
            Assert.That(output, Does.Contain("AutoSaveOnQuitTimeout = 1234"));
        }

        [Test]
        public void BuildCsContent_StringWithSpecialChars_Escaped()
        {
            string output = InvokeBuildCsContent(new SaveSettings
            {
                FileName = "weird\\name",       // a\b
                SaveExtension = ".with\"quote",  // contains "
                MetaExtension = "tab\there",     // contains \t
            });

            Assert.That(output, Does.Contain("FileName = \"weird\\\\name\""));
            Assert.That(output, Does.Contain("SaveExtension = \".with\\\"quote\""));
            Assert.That(output, Does.Contain("MetaExtension = \"tab\\there\""));
        }

        [Test]
        public void BuildCsContent_NullString_EmitsNullLiteral()
        {
            string output = InvokeBuildCsContent(new SaveSettings { FileName = null });
            Assert.That(output, Does.Contain("FileName = null"));
        }

        #endregion

        #region BuildAsmdefContent

        [Test]
        public void BuildAsmdefContent_HasNameAndCoreReference()
        {
            string output = InvokeBuildAsmdefContent();
            Assert.That(output, Does.Contain("\"name\": \"SaveKeeper.Generated\""));
            Assert.That(output, Does.Contain("GUID:b94cf75cc62c7154faf8c40a883ed3af"));
            Assert.That(output, Does.Contain("\"autoReferenced\": true"));
        }

        #endregion

        #region Format helpers — bool

        [TestCase(true, "true")]
        [TestCase(false, "false")]
        public void FormatBool_ReturnsLowercaseLiteral(bool input, string expected)
        {
            Assert.AreEqual(expected, (string)InvokeStaticPrivate("FormatBool", input));
        }

        #endregion

        #region Format helpers — float

        [TestCase(0f, "0f")]
        [TestCase(1.5f, "1.5f")]
        [TestCase(-2.25f, "-2.25f")]
        public void FormatFloat_AppendsFSuffix_InvariantCulture(float input, string expected)
        {
            Assert.AreEqual(expected, (string)InvokeStaticPrivate("FormatFloat", input));
        }

        #endregion

        #region Format helpers — string

        [TestCase(null, "null")]
        [TestCase("", "\"\"")]
        [TestCase("hello", "\"hello\"")]
        public void FormatString_Simple(string input, string expected)
        {
            Assert.AreEqual(expected, (string)InvokeStaticPrivate("FormatString", input));
        }

        [Test]
        public void FormatString_Backslash_EscapedDouble()
        {
            // Input: a\b  →  expected C# literal: "a\\b"
            string result = (string)InvokeStaticPrivate("FormatString", "a\\b");
            Assert.AreEqual("\"a\\\\b\"", result);
        }

        [Test]
        public void FormatString_DoubleQuote_Escaped()
        {
            // Input: ab"cd  →  expected C# literal: "ab\"cd"
            string result = (string)InvokeStaticPrivate("FormatString", "ab\"cd");
            Assert.AreEqual("\"ab\\\"cd\"", result);
        }

        [TestCase("\n", "\\n")]
        [TestCase("\r", "\\r")]
        [TestCase("\t", "\\t")]
        public void FormatString_ControlChars_EscapedToBackslashLetter(string input, string escaped)
        {
            string result = (string)InvokeStaticPrivate("FormatString", input);
            Assert.AreEqual("\"" + escaped + "\"", result);
        }

        #endregion

        #region Public API

        [Test]
        public void Generate_NullSettings_ThrowsArgumentNullException()
        {
            Assert.Throws<System.ArgumentNullException>(() => SaveKeeperSettingsGenerator.Generate(null));
        }

        #endregion

        #region Reflection helpers

        private static string InvokeBuildCsContent(SaveSettings s)
        {
            MethodInfo m = typeof(SaveKeeperSettingsGenerator).GetMethod(
                "BuildCsContent", BindingFlags.Static | BindingFlags.NonPublic);
            Assert.IsNotNull(m, "BuildCsContent reflection lookup failed — was the method renamed?");
            return (string)m.Invoke(null, new object[] { s });
        }

        private static string InvokeBuildAsmdefContent()
        {
            MethodInfo m = typeof(SaveKeeperSettingsGenerator).GetMethod(
                "BuildAsmdefContent", BindingFlags.Static | BindingFlags.NonPublic);
            Assert.IsNotNull(m, "BuildAsmdefContent reflection lookup failed — was the method renamed?");
            return (string)m.Invoke(null, null);
        }

        private static object InvokeStaticPrivate(string methodName, object arg)
        {
            MethodInfo m = typeof(SaveKeeperSettingsGenerator).GetMethod(
                methodName, BindingFlags.Static | BindingFlags.NonPublic);
            Assert.IsNotNull(m, $"{methodName} reflection lookup failed — was the method renamed?");
            return m.Invoke(null, new[] { arg });
        }

        #endregion
    }
}
