// <auto-generated />
// Generated by SaveKeeper. Do not edit — changes will be overwritten.
// Source: ProjectSettings/SaveKeeperSettings.json
namespace ThanhDV.SaveKeeper.Core
{
    public static class SaveKeeperSettings
    {
        public static SaveSettings Create() => new SaveSettings
        {
            UseEncryption = true,
            FileName = "Default",
            SaveExtension = ".sav",
            MetaExtension = ".meta",
            EnableAutoSave = true,
            AutoSaveTime = 300f,
            AutoSaveOnQuit = true,
            AutoSaveOnQuitTimeout = 3000,
        };
    }
}
