using System;
using System.Globalization;
using System.IO;
using System.Text;
using ThanhDV.SaveKeeper.Core;
using UnityEditor;

namespace ThanhDV.SaveKeeper.Editor
{
    /// <summary>
    /// Generates the runtime <c>SaveKeeperSettings</c> factory class and accompanying asmdef
    /// into Assets/Plugins/SaveKeeper/, based on a <see cref="SaveSettings"/> instance.
    /// </summary>
    /// <remarks>
    /// Output:
    /// <list type="bullet">
    /// <item>Assets/Plugins/SaveKeeper/SaveKeeperSettings.cs — always overwritten.</item>
    /// <item>Assets/Plugins/SaveKeeper/SaveKeeper.Generated.asmdef — only written if missing.</item>
    /// </list>
    /// The generated .cs is the authoritative source of settings at runtime; the JSON file in
    /// ProjectSettings/ is only consulted at edit time by the settings window.
    /// </remarks>
    public class SaveKeeperSettingsGenerator
    {
        private const string OUTPUT_DIR = "Assets/Plugins/SaveKeeper";
        private const string CS_FILE_NAME = "SaveKeeperSettings.cs";
        private const string ASMDEF_FILE_NAME = "SaveKeeper.Generated.asmdef";
        private const string CORE_ASMDEF_GUID = "b94cf75cc62c7154faf8c40a883ed3af";

        /// <summary>
        /// Writes the factory .cs (always) and asmdef (only if missing) into OUTPUT_DIR, then
        /// triggers an asset database refresh so Unity picks up the new files and recompiles.
        /// </summary>
        public static void Generate(SaveSettings settings)
        {
            if (settings == null) throw new ArgumentNullException(nameof(settings));

            if (!Directory.Exists(OUTPUT_DIR)) Directory.CreateDirectory(OUTPUT_DIR);

            string csPath = Path.Combine(OUTPUT_DIR, CS_FILE_NAME);
            File.WriteAllText(csPath, BuildCsContent(settings));

            string asmdefPath = Path.Combine(OUTPUT_DIR, ASMDEF_FILE_NAME);
            if (!File.Exists(asmdefPath)) File.WriteAllText(asmdefPath, BuildAsmdefContent());

            AssetDatabase.Refresh();
        }

        private static string BuildCsContent(SaveSettings s)
        {
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by SaveKeeper. Do not edit — changes will be overwritten.");
            sb.AppendLine("// Source: ProjectSettings/SaveKeeperSettings.json");
            sb.AppendLine("namespace ThanhDV.SaveKeeper.Core");
            sb.AppendLine("{");
            sb.AppendLine("    [UnityEngine.Scripting.Preserve]");
            sb.AppendLine("    public static class SaveKeeperSettings");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.Scripting.Preserve]");
            sb.AppendLine("        public static SaveSettings Create() => new SaveSettings");
            sb.AppendLine("        {");
            sb.AppendLine($"            UseEncryption = {FormatBool(s.UseEncryption)},");
            sb.AppendLine($"            FileName = {FormatString(s.FileName)},");
            sb.AppendLine($"            SaveExtension = {FormatString(s.SaveExtension)},");
            sb.AppendLine($"            MetaExtension = {FormatString(s.MetaExtension)},");
            sb.AppendLine($"            EnableAutoSave = {FormatBool(s.EnableAutoSave)},");
            sb.AppendLine($"            AutoSaveTime = {FormatFloat(s.AutoSaveTime)},");
            sb.AppendLine($"            AutoSaveOnQuit = {FormatBool(s.AutoSaveOnQuit)},");
            sb.AppendLine($"            AutoSaveOnQuitTimeout = {s.AutoSaveOnQuitTimeout.ToString(CultureInfo.InvariantCulture)},");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildAsmdefContent()
        {
            return @"{
                        ""name"": ""SaveKeeper.Generated"",
                        ""rootNamespace"": """",
                        ""references"": [
                            ""GUID:" + CORE_ASMDEF_GUID + @"""
                        ],
                        ""includePlatforms"": [],
                        ""excludePlatforms"": [],
                        ""allowUnsafeCode"": false,
                        ""overrideReferences"": false,
                        ""precompiledReferences"": [],
                        ""autoReferenced"": true,
                        ""defineConstraints"": [],
                        ""versionDefines"": [],
                        ""noEngineReferences"": false
                    }";
        }

        private static string FormatBool(bool b) => b ? "true" : "false";

        private static string FormatFloat(float f) => f.ToString("R", CultureInfo.InvariantCulture) + "f";

        private static string FormatString(string s)
        {
            if (s == null) return "null";
            StringBuilder sb = new();
            sb.Append('"');
            foreach (char c in s)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default: sb.Append(c); break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
